language: python

env:
    global:
      - PSQL_USERNAME=francisco_morales
      - PSQL_PASS=francisco123*
      - PSQL_DBNAME=francisco_morales_d
      - PSQL_HOST=localhost
      - PSQL_PORT=5432

services:
    - postgresql
install:
    - pip install django djangorestframework djangorestframework-simplejwt PyJWT django-cors-headers psycopg2-binary
before_script:
  - psql -c "CREATE DATABASE francisco_morales_d;" -U postgres
  - psql -c "CREATE USER francisco_morales WITH PASSWORD 'francisco123*';" -U postgres
  - psql -c "ALTER USER francisco_morales CREATEDB;" -U postgres
  
script:
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test