# Generated by Django 3.2.9 on 2021-11-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='int_number',
            field=models.IntegerField(null=True),
        ),
    ]
