# Generated by Django 3.2.9 on 2021-11-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_direction_int_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='int_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
